apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: git-repo
              mountPath: /usr/share/nginx/html  # Mounting the repo contents at the Nginx expected location
            - name: app1-index
              mountPath: /usr/share/nginx/html/index.html
              subPath: /tmp/git/apps/k8s-apps/app1/index.html  # Mounting the specific index.html for app1
        - name: git-sync
          image: k8s.gcr.io/git-sync:v3.0.0
          env:
            - name: GIT_SYNC_REPO
              value: "https://github.com/pawan-kumar1/apps.git"
            - name: GIT_SYNC_BRANCH
              value: "b1"
            - name: GIT_SYNC_DEST
              value: "/mnt/git"  # Directory where git-sync will place the repo
          volumeMounts:
            - name: git-repo
              mountPath: /mnt/git  # Syncing the repo content to this location
      volumes:
        - name: git-repo
          emptyDir: {}  # Temporary storage for syncing the repo
        - name: app1-index
          emptyDir: {}  # Temporary storage for syncing the app1 index.html file
