apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: local-html
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html
      volumes:
        - name: local-html
          hostPath:
            path: k8s-apps/app1/index.html  # Change this to your local file path
            type: File
