apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: git-repo
              mountPath: /usr/share/nginx/html  # Mount the entire repo contents here
            - name: app1-index
              mountPath: /usr/share/nginx/html/index.html  # Mount the specific index.html from app1
              subPath: index.html  # Mount the specific file (not the whole directory)
        - name: git-sync
          image: k8s.gcr.io/git-sync:v3.0.0
          env:
            - name: GIT_SYNC_REPO
              value: "https://github.com/pawan-kumar1/apps.git"
            - name: GIT_SYNC_BRANCH
              value: "b1"
            - name: GIT_SYNC_DEST
              value: "/mnt/git"  # Directory where git-sync will clone the repo
          volumeMounts:
            - name: git-repo
              mountPath: /mnt/git  # Mount the cloned repo here
      volumes:
        - name: git-repo
          emptyDir: {}  # Temporary storage for the repo files
        - name: app1-index
          emptyDir: {}  # Temporary storage for app1/index.html
