apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: ns-localstorage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: local-storage
              mountPath: /usr/share/nginx/html  # Mount the local storage to this path
      volumes:
        - name: local-storage
          persistentVolumeClaim:
            claimName: local-pvc

