apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-pvc
  namespace: ns-localstorage  # Ensure this matches your namespace
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: local-storage
