apiVersion: apps/v1
kind: Deployment
metadata:
  name: rhythm-deployment
  namespace: myapps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rhythmapp
  template:
    metadata:
      labels:
        app: rhythmapp
    spec:
      containers:
        - name: rhythmapp
          image: pawan1/u16_apache2_php5:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: local-storage
              mountPath: /var/www/html  # Updated mount path
          command: ["sh", "-c", "service apache2 start && tail -f /dev/null"]
          env:
            - name: APP_ENV
              value: "production"
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
      volumes:
        - name: local-storage
          persistentVolumeClaim:
            claimName: local-pvc
