apiVersion: v1
kind: Service
metadata:
  name: rhythmapp-service
 namespace: myapps
spec:
  selector:
    app: rhythmapp
  type: NodePort
  ports:
    - protocol: TCP
      port: 80          # Service port (ClusterIP access)
      targetPort: 80     # Container port
      nodePort: 30002    # Fixed NodePort

